"use client";

import "./globals.css";

import { createContext, useState } from "react";
import { Header } from "@/components/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const TokenContext = createContext();

export default function RootLayout({ children }) {
  const [token, setToken] = useState(localStorage.getItem("token"));
  return (
    <html>
      <body>
        <TokenContext.Provider value={{ token, setToken }}>
          <Header />
          {children}
        </TokenContext.Provider>
      </body>
    </html>
  );
}
